### ISSUE TITLE
RPI4 Segmentation Fault

### ISSUE THREAD

**Issue by AndyCXL** [freegroup/HoruCNC#3]
Great looking tool, and very keen to get this up and running.

On Raspberry Pi4 the app starts, outputs various filter messages, then the app window appears and the messages continue, then it exits with a segmentation fault. I have increased OS swap memory from 100 to 2048, but the issue still happens.

On macOS Monterey there is the issue of OpenGL being deprecated by Apple, which is something I am still trying to work around, but no success as yet.

The RPi4 is my main goal to get up and running

**Comment by AndyCXL** [comment]
Increasing RPI GPU memory (to 256k) and restricting use of HoruCNC to small monochrome images results in 'some functionality' but the on-display gcode preview does not display. A call-error trace shows this to be;

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 204, in paintGL
    self.setProjection(region=region)
  File "/home/pi/.local/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 126, in setProjection
    glMatrixMode(GL_PROJECTION)
  File "/home/pi/.local/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
	err = 1282,
	baseOperation = glMatrixMode,
	cArguments = (GL_PROJECTION,)
)

Does this help understand the issue at all? Is it GPU resource limitations, or is something else happening?
